Repository chanzuckerberg/edu-design-system, pull requests merged in 2023-07, with the labels that each got.

#1672 chore(deps): update all non-major dependencies
  package.json
  yarn.lock
Labels: npm-dependencies

#1677 chore(deps): update dependency stylelint to v15.10.1 [security]
  package.json
  yarn.lock
Labels: npm-dependencies

#1698 fix: make sure all var properties exist on one line
  .storybook/pages/WireframeDemo/GlobalStyles.module.css
  CHANGELOG.md
  README.md
  package.json
  src/components/Badge/Badge.module.css
  src/components/ClickableStyle/ClickableStyle.module.css
  src/components/DataBar/DataBar.module.css
  src/components/DataBarSegment/DataBarSegment.module.css
  src/components/Menu/Menu.module.css
  src/components/NumberIcon/NumberIcon.module.css
  src/components/Skeleton/Skeleton.module.css
  src/components/Slider/Slider.module.css
  src/components/Tag/Tag.module.css
  src/design-tokens/mixins.css
Labels: hotfix

#1657 refactor!: remove deprecated dropdown
  src/components/ButtonDropdown/ButtonDropdown.module.css
  src/components/ButtonDropdown/ButtonDropdown.stories.tsx
  src/components/ButtonDropdown/ButtonDropdown.test.tsx
  src/components/ButtonDropdown/ButtonDropdown.tsx
  src/components/ButtonDropdown/__snapshots__/ButtonDropdown.test.tsx.snap
  src/components/ButtonDropdown/index.ts
  src/components/Dropdown/Dropdown.module.css
  src/components/Dropdown/Dropdown.stories.module.css
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.test.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/components/Dropdown/index.ts
  src/components/DropdownButton/DropdownButton.module.css
  src/components/DropdownButton/DropdownButton.tsx
  src/components/DropdownButton/index.ts
  src/components/DropdownMenu/DropdownMenu.module.css
  src/components/DropdownMenu/DropdownMenu.stories.tsx
  src/components/DropdownMenu/DropdownMenu.test.ts
  src/components/DropdownMenu/DropdownMenu.tsx
  src/components/DropdownMenu/__snapshots__/DropdownMenu.test.ts.snap
  src/components/DropdownMenu/index.ts
  src/components/DropdownMenuItem/DropdownMenuItem.tsx
  src/components/DropdownMenuItem/index.ts
  src/index.ts
Labels: next-major

#1711 docs(colors)!: remove old colors and convert to input and show figma token
  .storybook/components/ColorList/ColorList.module.css
  .storybook/components/ColorList/ColorList.tsx
  .storybook/components/DesignTokens/Tier1/Colors.jsx
  .storybook/components/DesignTokens/Tier1/Colors.tsx
  .storybook/components/TokenSpecimen/TokenSpecimen.css
  .storybook/components/TokenSpecimen/TokenSpecimen.tsx
  .storybook/data/tokens.json
  src/design-tokens/tier-1-definitions/colors.json
  src/tokens-dist/css/variables.css
  src/tokens-dist/json/variables-nested.json
  src/tokens-dist/ts/colors.ts
Labels: next-major
