Repository chanzuckerberg/edu-design-system, pull requests merged in 2024-07, with the labels that each got.

#2011 feat(Modal): add height property to modal API
  .storybook/preview.tsx
  src/components/Modal/Modal.module.css
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/__snapshots__/Modal.test.tsx.snap
Labels: feature request

#2010 docs: add clarity to what EDS repository provides
  LICENSE
  README.md
Labels: documentation

#2017 chore(deps): update all non-major dependencies
  .storybook/Theme.ts
  package.json
  src/components/Avatar/Avatar.test.ts
  src/components/Badge/Badge.test.tsx
  src/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/components/Hr/Hr.test.ts
  src/components/LoadingIndicator/LoadingIndicator.test.ts
  src/components/Menu/Menu.test.tsx
  src/components/PageNotification/PageNotification.test.ts
  src/components/Popover/Popover.test.tsx
  src/components/Select/Select.test.tsx
  src/components/Skeleton/Skeleton.test.ts
  src/components/TabGroup/TabGroup.test.tsx
  src/components/Tag/Tag.test.ts
  src/components/Tooltip/Tooltip.test.tsx
  yarn.lock
Labels: npm-dependencies

#2022 chore(deps): update all non-major dependencies
  package.json
  yarn.lock
Labels: npm-dependencies

#2026 chore(deps): update dependency typescript to ^5.5.4
  package.json
  yarn.lock
Labels: npm-dependencies
